### ISSUE TITLE
提问cookies的格式是什么

### ISSUE THREAD

**Issue by 56luffy** [Olvi73/reserve-seat-in-lib#4]
我用的是黄鸟抓包,给我的是分段的信息

SERVERID=
Hm_lvt_7ecd21a13263a714793f376c18038a87=
Hm_lpvt_7ecd21a13263a714793f376c18038a87=
我输入的时候如何输入呢?
"SERVERID"="00000",
"Hm_lvt_7ecd21a13263a714793f376c18038a87"="00",
这种还是如何?

**Comment by Olvi73** [comment]
代码中22行左右
```
mcookies = dict(FROM_TYPE="weixin" ,wechatSESS_ID="",
        Hm_lvt_7ecd21a13263a714793f376c18038a87="",
        Hm_lpvt_7ecd21a13263a714793f376c18038a87="",
    SERVERID=""
)
```
放在等号后面的冒号中
